yarnPath: .yarn/releases/yarn-2.0.0-rc.33.cjs

packageExtensions:
  "@uifabric/styling@*":
    dependencies:
      "@types/react": "16.8.6"
      "@types/react-dom": "16.8.5"
      "react": "16.8.6"
      "react-dom": "16.8.6"
  "@fluentui/react-icons@*":
    dependencies:
      "@types/react": "16.8.6"